eureka:
  client:
    register-with-eureka: true

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/course/**
        - id: results
          uri: http://localhost:8074
          predicates:
            - Path=/api/result/**
        - id: candidate
          uri: http://localhost:8034
          predicates:
            - Path=/api/candidate/**
        - id: elector
          uri: http://localhost:8024
          predicates:
            - Path=/api/elector/**
